baseURL = 'https://plataformas-moviles.vercel.app'
languageCode = 'es-AR'
defaultContentLanguage = 'es'
title = 'Plataformas Móviles'
disableKinds = ['taxonomy', 'term']
theme = ["reveal-hugo"]
[params]
	mainSections = ['clases']
	repository = 'https://github.com/tehuel/plataformas-moviles'

[pagination]
	pagerSize = 999

[frontmatter]
	date = [':filename', ':default']

[markup.highlight]
    style = 'vs'

[markup.goldmark.renderer]
	unsafe = true

[markup.goldmark.parser.attribute]
	block = true
[outputFormats.Reveal]
	mediaType = "text/html"
	isHTML = true

[params.reveal_hugo]
	theme = "simple"
